### ISSUE TITLE
Add .astro file support

### ISSUE THREAD

**Issue by huotarih** [rohit-chouhan/animate-pure-css-snippet#1]
[Astro](https://astro.build) is a up and coming framework on which you write basic html.
This extension would be great for astro developers to include animations to their pages easily.

**Comment by rohit-chouhan** [comment]
hey [huotarih](https://github.com/huotarih), thanks for the report. Astro supported has been added [🙂](https://emojipedia.org/slightly-smiling-face/)

**Comment by huotarih** [comment]
Thanks for adding it to the animate.css extension, would it be possible to also add it for this snippet extension?
I would just love to easily use these animation classes, the animate.css extension by itself doesn't really help here since I don't use custom css files, just tailwind and animate libraries.

**Comment by rohit-chouhan** [comment]
We have two extension here:-
- Get Pure CSS of animate.css [https://marketplace.visualstudio.com/items?itemName=rohit-chouhan.animate-css](https://marketplace.visualstudio.com/items?itemName=rohit-chouhan.animate-css)
- Get classes of animate.css [https://marketplace.visualstudio.com/items?itemName=rohit-chouhan.animate-css-snippet](https://marketplace.visualstudio.com/items?itemName=rohit-chouhan.animate-css-snippet)

**Comment by huotarih** [comment]
Yes, but only https://marketplace.visualstudio.com/items?itemName=rohit-chouhan.animate-css was updated.

Can you also update https://marketplace.visualstudio.com/items?itemName=rohit-chouhan.animate-css-snippet ? :) ❤️

**Comment by rohit-chouhan** [comment]
**.astro** support added for both snippet, thanks for report. 🙂
